# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takeItem_demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lblCountry = QtWidgets.QLabel(Dialog)
        self.lblCountry.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.lblCountry.setObjectName("lblCountry")
        self.lineEdit_Country = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Country.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.lineEdit_Country.setObjectName("lineEdit_Country")
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.btnAdd.setObjectName("btnAdd")
        self.btnTake2 = QtWidgets.QPushButton(Dialog)
        self.btnTake2.setGeometry(QtCore.QRect(20, 150, 75, 23))
        self.btnTake2.setObjectName("btnTake2")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(110, 80, 256, 192))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblCountry.setText(_translate("Dialog", "Enter Country"))
        self.btnAdd.setText(_translate("Dialog", "Add"))
        self.btnTake2.setText(_translate("Dialog", "Take Item 2"))
