# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radiobtn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lblFirstNumber = QtWidgets.QLabel(Dialog)
        self.lblFirstNumber.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.lblFirstNumber.setObjectName("lblFirstNumber")
        self.lblSecondNumber = QtWidgets.QLabel(Dialog)
        self.lblSecondNumber.setGeometry(QtCore.QRect(20, 50, 111, 16))
        self.lblSecondNumber.setObjectName("lblSecondNumber")
        self.lineEdit_First = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_First.setGeometry(QtCore.QRect(150, 20, 113, 20))
        self.lineEdit_First.setObjectName("lineEdit_First")
        self.lineEdit_Second = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Second.setGeometry(QtCore.QRect(150, 50, 113, 20))
        self.lineEdit_Second.setObjectName("lineEdit_Second")
        self.radioButton_Add = QtWidgets.QRadioButton(Dialog)
        self.radioButton_Add.setGeometry(QtCore.QRect(30, 100, 82, 17))
        self.radioButton_Add.setObjectName("radioButton_Add")
        self.radioButton_Subtract = QtWidgets.QRadioButton(Dialog)
        self.radioButton_Subtract.setGeometry(QtCore.QRect(30, 130, 82, 17))
        self.radioButton_Subtract.setObjectName("radioButton_Subtract")
        self.radioButton_Multiply = QtWidgets.QRadioButton(Dialog)
        self.radioButton_Multiply.setGeometry(QtCore.QRect(30, 160, 82, 17))
        self.radioButton_Multiply.setObjectName("radioButton_Multiply")
        self.radioButton_Divide = QtWidgets.QRadioButton(Dialog)
        self.radioButton_Divide.setGeometry(QtCore.QRect(30, 190, 82, 17))
        self.radioButton_Divide.setObjectName("radioButton_Divide")
        self.lblResult = QtWidgets.QLabel(Dialog)
        self.lblResult.setGeometry(QtCore.QRect(80, 230, 71, 16))
        self.lblResult.setObjectName("lblResult")
        self.pushButton_Compute = QtWidgets.QPushButton(Dialog)
        self.pushButton_Compute.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.pushButton_Compute.setObjectName("pushButton_Compute")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblFirstNumber.setText(_translate("Dialog", "Enter First Number"))
        self.lblSecondNumber.setText(_translate("Dialog", "Enter Second Number"))
        self.radioButton_Add.setText(_translate("Dialog", "Add"))
        self.radioButton_Subtract.setText(_translate("Dialog", "Subtract"))
        self.radioButton_Multiply.setText(_translate("Dialog", "Multiply"))
        self.radioButton_Divide.setText(_translate("Dialog", "Divide"))
        self.lblResult.setText(_translate("Dialog", "Result"))
        self.pushButton_Compute.setText(_translate("Dialog", "Compute"))
